---
# - alias: ALIAS
#   url: https://example.org

- alias: index
  url: https://github.com/qoomon/short-urls

- alias: q
  url: https://qoo.monster
  
- alias: [ Conventional-Commits, git-cc ]
  url: https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13
